apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-retry-fun
  namespace: new-aks-project
  annotations:
    azure.workload.identity/client-id: "12324234"
  labels:
    azure.workload.identity/use: "true"
