apiVersion: v1
kind: Service
metadata:
  name: grpc-retry-fun
  namespace: a-project
  labels:
    app: grpc-retry-fun
spec:
  type: ClusterIP
  selector:
    app: grpc-retry-fun
  ports:
  - name: grpc
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
